server.ssl.key-store=classpath:hello-service.p12
server.ssl.key-store-password=hello-service
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=hello-service
server.ssl.key-password=hello-service
server.port=8085
server.ssl.port=8085

logging.threshold.console=TRACE
logging.threshold.file=INFO
logging.level.root=INFO
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.strata=TRACE
