server.ssl.key-store=classpath:hello-service.p12
server.ssl.key-store-password=hello-service
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=hello-service
server.ssl.key-password=hello-service
server.port=8081
server.ssl.port=8081
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

