jakarta.persistence.persistence-unit=outbox-server-domain
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sayinadmin
spring.datasource.password=ENC(DGMAt3Zo2x+kQlgznmN6xJZj5pQvwHVE5AyeojZ3wiV9ShWYRE81IwZTRF9mu1O5)
spring.datasource.url=jdbc:postgresql://sayin-development.postgres.database.azure.com:5432/sayin-platform
spring.jpa.show-sql=true
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.mapping-resources=Outbox.orm.xml
spring.guice.dedup=true