plugins {
    id 'java-library'
}

sourceSets {
    main.java.srcDirs = ['src/main/java','build/generated-java']
    main.resources.srcDirs = ['src/main/resources','src/main/schema']
    test.java.srcDirs = ['src/unused']
    test.resources.srcDirs = ['src/unused']
}


apply plugin: 'maven-publish'

group 'strata.outbox'
version "$major$minor$patch"

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
}

publishing {
    publications {
        StrataOutboxClient(MavenPublication) {
            artifactId = 'strata-outbox-client'
            from components.java

            repositories {
                maven {
                    name "GitHubPackages"
                    url "https://maven.pkg.github.com/StrataFrameworkSet/repository"
                    credentials {
                        username = "$System.env.REPOSITORY_USER"
                        password = "$System.env.REPOSITORY_PASSWORD"
                    }
                }
            }
        }
    }
}

dependencies {
    api project(":Components:Strata.Outbox.Service")
    api "org.springframework.boot:spring-boot-starter-security:$springboot_version"
    api "strata.client:strata-client-core:$version"
    api "strata.client:strata-client-spring:$version"
    api "strata.foundation:strata-foundation-kafka:$version"
    api 'org.jboss.resteasy:resteasy-client:6.2.7.Final'
    api 'org.jboss:jandex:3.1.6'
}